### ISSUE TITLE
panic: The request failed and i do not know why: response.status =  3

### ISSUE THREAD

**Issue by CSimpiFoN** [jimmypw/adcs#2]
The application drops a kind of unusable general error message:
"panic: The request failed and i do not know why: response.status =  3"

It is quite hard to troubleshoot.

Command ran:
`~/go/bin/adcscli -csr '/tmp/certs/cert.csr' -out '/tmp/certs/cert.crt' -username 'domain\user' -password 'securepassword' -template 'Web Server key' -url 'https://ca.domain.local/certsrv'`

Full error message:
`panic: The request failed and i do not know why: response.status =  3`

`goroutine 1 [running]:`
`github.com/jimmypw/adcs.(*WebEnrollmentNewRequest).Submit(0xc00008ecc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000d6000)`
`       /home/user/go/src/github.com/jimmypw/adcs/webenrollmentnewrequest.go:54 +0x597
github.com/jimmypw/adcs.(*WebEnrollmentServer).SubmitNewRequest(0xc00008ec90, 0xc0000d6000, 0x74e, 0x94e, 0x7ffff7966999, 0xe, 0x0, 0x0, 0x0, 0x0, ...)`
`        /home/user/go/src/github.com/jimmypw/adcs/webenrollmentserver.go:28 +0xfe
main.main()`
`        /home/user/go/src/github.com/jimmypw/adcs/cli/adcscli/main.go:88 +0x437`

**Comment by jimmypw** [comment]
Please upgrade to the latest version, it looks like the user requesting the certificate does not have privileges on the template specified. In a later version unauthorized requests are handled properly.

**Comment by jimmypw** [comment]
Actually scrap that, we just encountered the same issue at work. Still upgrade but remove the domain part of the username so just 'username' not 'domain\username' or 'username@fqdn'
